### PR TITLE
created catch all for exceptions to handle them properly

### PR DESCRIPTION
**Pull request by tmbo**
**Proposed changes**:
- handle exceptions thrown in custom actions
- return a 500 response code as well as information about the error 
- compatible change since we already by default returned a 500 (sanic default). but exception was not properly logged to logger

### CODE REVIEW

**Review by ancalita — APPROVED** [review]
LGTM 💯

**Comment by raoulvm** [comment]
Great, thank you @tmbo

**Comment by raoulvm** [comment]
Oh, I just noticed 2.8.9 was already released. Will this be 2.8.10, and what is the release schedule?

**Comment by tmbo** [comment]
@raoulvm we cut that slightly to early but we already prepared a follow up release: https://github.com/RasaHQ/rasa-sdk/pull/846. the change is part of 2.8.10

We always release patches when we need them / on demand (only minors/majors are scheduled releases for us).

**Comment by tmbo** [comment]
2.8.10 is available on pypi https://pypi.org/project/rasa-sdk/2.8.10/

**Pull request merged**
