### PR TITLE
Logging to file for action server

### PR DESCRIPTION
**Pull request by dingusagar**
**Proposed changes**:
- Added command line argument option for the action server to save logs to a log file.

**Status (please check what you already did)**:
- [X] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

### CODE REVIEW

**Comment by dingusagar** [comment]
Linked issue here #161

**Comment by roniemartinez** [comment]
Awesome! Hope the project owners review this. 💯

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @melindaloubser1 will take a look at it as soon as possible ✨

**Comment by iwt-kschoenrock** [comment]
Wouldn't it be better to use a [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler) directly? This would allow you to set `backupCount` to avoid eventually running out of space because of old logs.
Maybe let the user configure the number of backup files kept around?

**Comment by dingusagar** [comment]
> Wouldn't it be better to use a [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler) directly? This would allow you to set `backupCount` to avoid eventually running out of space because of old logs.
> Maybe let the user configure the number of backup files kept around?

[RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler)  seems to be a better choice than [FileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.FileHandler). `backupCount` argument can be kept to 0 by default so that the default behaviour is a single file growing indefinitely. And user can specify `backupCount` as a command line argument. 

What do you think should be the value of `maxBytes` argument. Do you feel that needs to be configurable as well? @iwt-kschoenrock /  @roniemartinez 
Shall I add this enhancement to the PR. Any other concerns? @melindaloubser1

**Comment by iwt-kschoenrock** [comment]
> [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler) seems to be a better choice than [FileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.FileHandler). `backupCount` argument can be kept to 0 by default so that the default behaviour is a single file growing indefinitely. And user can specify `backupCount` as a command line argument.
> 
> What do you think should be the value of `maxBytes` argument. Do you feel that needs to be configurable as well? @iwt-kschoenrock / @roniemartinez
> Shall I add this enhancement to the PR. Any concerns / thoughts? @melindaloubser1

I don't have any current examples of how big the Rasa Logs would be, maybe someone from Rasa could give an estimate? But I agree that `backuptCount` and `maxBytes` should be configurable.

This functionality is important for us, as we're looking for ways to configure ingestion of multi-line logs in Datadog, and the log file would probably be the easiest way to achieve it, apart from the nonplusultra solution, which would be allowing a custom log formatter or [log configuration file to be provided](https://docs.python.org/3/library/logging.config.html#configuration-file-format).

**Comment by melindaloubser1** [comment]
The action server runs separately from the rasa server, so logging to files for custom actions should be configured on the action server itself (whether rasa-sdk or another action server). The changes look like they're configuring logging of all logs to a file (for the rasa server).

**Comment by dingusagar** [comment]
> The action server runs separately from the rasa server, so logging to files for custom actions should be configured on the action server itself (whether rasa-sdk or another action server). The changes look like they're configuring logging of all logs to a file (for the rasa server). Can you clarify the desired behaviour of the change?

valid point. I have updated the code to configure logging only for action server. I gave "rasa_sdk" as the name for the named logger. so now the configuration is only for loggers within the moduel rasa_sdk. 

Could you review my latest changes? @melindaloubser1 
Thanks

**Review by melindaloubser1 — CHANGES_REQUESTED** [review]
The logging to file works great, but it seems to set the logging level to `debug` regardless of what is passed as the log level - could you look into that?

**Comment by dingusagar** [comment]
> The logging to file works great, but it seems to set the logging level to `debug` regardless of what is passed as the log level - could you look into that?

Ok I will look into it

**Comment by dingusagar** [comment]
> The logging to file works great, but it seems to set the logging level to `debug` regardless of what is passed as the log level - could you look into that?

Hi @melindaloubser1 
I have pushed the fix for setting the log level of root logger of the project  from the command line args.

I noticed that the logger for matplotlib is set to WARN and logger for loglevel for sanic logger is set by environment variables. I have't changed any of those. But let me know if these loglevels also needs to controlled by the arguement passed in the command line args

**Comment by wochinge** [comment]
fixing the `code_quality` step [here](https://github.com/RasaHQ/rasa-sdk/pull/354). Sorry for the inconvenience!

**Review by melindaloubser1 — CHANGES_REQUESTED** [review]
Can you run  `make formatter` and apply the changes? The linting step is failing.

**Comment by dingusagar** [comment]
> Can you run `make formatter` and apply the changes? The linting step is failing.

sure @melindaloubser1 
have made the changes for the errors given by `make lint`

**Review by melindaloubser1 — APPROVED** [review]

**Comment by melindaloubser1** [comment]
Sorry one more thing, can you add a changelog entry please? You'll find instructions for that in the changelog/README.md

**Comment by dingusagar** [comment]
> Sorry one more thing, can you add a changelog entry please? You'll find instructions for that in the changelog/README.md

added a changelog entry.

**Pull request merged**
