### PR TITLE
reformat code by using black

### PR DESCRIPTION
**Pull request by howl-anderson**
**Proposed changes**:
- reformat code by using black

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @akelad will take a look at it as soon as possible ✨

**Comment by akelad** [comment]
@wochinge is this not automatically done by our CI? our flake8 linter is failing during those steps in any case

**Comment by howl-anderson** [comment]
@akelad I didn't see the Code Quality check

**Comment by howl-anderson** [comment]
(Sorry, close the PR by accident) It seems that the current CI process missing the `Lint code` step.

**Comment by wochinge** [comment]
This is definitely done [here](https://github.com/RasaHQ/rasa-sdk/blob/cd664ccc7c51f657c4e5a80d9410d96f1ef65959/Makefile#L40) and that also shows up the in the logs.

Maybe you're using a different black version @howl-anderson ? The SDK tis using a newer version than Rasa Open Source

**Comment by howl-anderson** [comment]
I clone the repo yesterday, and I found that `make lint` will report format issue when I working on #366. Maybe previously merges are not passed the `code lint` step?

**Comment by wochinge** [comment]
Which `black` version do you have installed?

**Comment by howl-anderson** [comment]
`black, version 19.3b0` by `poetry run black --version`

**Comment by wochinge** [comment]
@howl-anderson `rasa-sdk` uses `20.8b1` in the CI which I believe has slightly different results.

**Comment by howl-anderson** [comment]
I don't familiar with `poetry`, maybe it does not update the env with the new dependency. I will try to figure out why.

**Comment by wochinge** [comment]
I'll close this for know 👍  `poetry install` in this repository should help 👍

**Pull request closed without merging**
