### PR TITLE
[ATO-2609] Add gRPC tracing

### PR DESCRIPTION
**Pull request by radovanZRasa**
Add tracing between Rasa and action server.

image

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation in the [rasaHQ/rasa](https://github.com/rasaHQ/rasa)
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

### CODE REVIEW

**Comment by Tawakalt** [comment]
@radovanZRasa We should do a quick check that [this](https://rasa.com/docs/rasa-pro/operating/tracing#debugging-custom-actions-performance) works with grpc as well.

**Comment by ancalita** [comment]
@radovanZRasa Do we know what are the errors in the screenshot you shared in the PR description? Referring to the spans with exclamation mark next to them.

**Comment by radovanZRasa** [comment]
> @radovanZRasa Do we know what are the errors in the screenshot you shared in the PR description? Referring to the spans with exclamation mark next to them.

Yea, I was testing Rasa with CALM bot from `calm-demo-bot` and action server from simple NLU bot because I did not want to lose time to install necessary dependencies for CALM bot's actions in my Rasa SDK virtual env. I only wanted to verify that tracing works.

**Comment by Tawakalt** [comment]
> @radovanZRasa Do we know what are the errors in the screenshot you shared in the PR description? Referring to the spans with exclamation mark next to them.

It's most likely the `missing domain` error log that should now be fixed.

**Comment by radovanZRasa** [comment]
> > @radovanZRasa Do we know what are the errors in the screenshot you shared in the PR description? Referring to the spans with exclamation mark next to them.
> 
> It's most likely the `missing domain` error log that should now be fixed.

They will also appear in this case. Good thing is that all calls are logged so everything is there. 

image

As image shows all calls are recorded.

For failed call log indicates that domain was not found:
image

**Comment by radovanZRasa** [comment]
> @radovanZRasa We should do a quick check that [this](https://rasa.com/docs/rasa-pro/operating/tracing#debugging-custom-actions-performance) works with grpc as well.

Verified:
image

**Review by Tawakalt — APPROVED** [review]

**Pull request merged**
