### PR TITLE
Skip publishing changelog for alphas or RCs

### LINKED ISSUE #360: Adjust Release CI scripts to work around Alphas / RCs
Clone issue of [this rasa-x counterpart](https://github.com/RasaHQ/rasa-x/issues/3695).
Adjustments required:
- Make sure changelog collection is skipped for alphas / RCs

### PR DESCRIPTION
**Pull request by mprazz**
**Proposed changes**:
- Fixes #360 
- @m-vdb I am not 100% sure this is the best way to skip the changelogs, I tried to harmonize the `continuous-integration.yml` with what we have in `rasa-x`. Do let me know if there's a better way to do this / if I'm missing something! 🙏  

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

### CODE REVIEW

**Review by tczekajlo — APPROVED** [review]
LGTM 👍

**Review by m-vdb — COMMENTED** [review]
it was [fixed differently for Rasa](https://github.com/RasaHQ/rasa/blob/9c8b9d9887c3aab62df4b47f260c9aa90c5216ef/scripts/publish_gh_release_notes.py#L80-L84), it might be a good idea to align the two solutions:

**Comment by mprazz** [comment]
@m-vdb you're right, it's a better way to do it too (more performant + alphas and RCs will have a small description)

**Review by m-vdb — APPROVED** [review]
🌊  thanks @mprazz !

**Pull request merged**
