### PR TITLE
Remove duplicate slot validation

### PR DESCRIPTION
**Pull request by yaput**
**Proposed changes**:
- Removed slot validation inside `_activate_if_required()`

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [X] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

### CODE REVIEW

**Comment by yaput** [comment]
Hi, i'm removing validation code inside the `_activate_if_required()` inside forms.py why? Because on forms.py inside `run()` line 519, we will validate the slot again. 
I tried to test before, and put `dispatcher.utter_message()` inside `validate_{slot_name}()` when it's not satisfied the validation and it will be executed twice. Is it expected?

**Comment by akelad** [comment]
hi @yaput this shouldn't be removed, because it is there to validate any slots that may have been filled prior to the activation of the form. E.g. if the user says "I want a chinese restaurant" and this activates the form, that cuisine entity needs to be validated.

**Comment by yaput** [comment]
hi @akelad yes, i agree with that, but it will be validated anyway right? After _activate_if_required, then the next code is _validate_if_required. Because right now it will execute the validate_{slot_name} twice, and my dispatcher.utter_message() to notify the user will run twice. I tried to use that case, and it will validate the slot anyway. I tried it on my local machine

**Comment by akelad** [comment]
hm actually i'm not too sure now, @Ghostvv any reason why we double validate there?

**Comment by Ghostvv** [comment]
`_activate_if_required` validates profiled slots. `_validate_if_required` validates slots that are set inside the last user input. But it validates different things: first time the slot, the second time the entity.  If a user provides the slot that is already filled or you fill the slots automatically with entities with the same name, it will be called it twice.

**Comment by yaput** [comment]
Hi @Ghostvv thanks for the explanation, if they are validating different thing, why they use the same function `validate()`?

**Comment by yaput** [comment]
Hi @Ghostvv thanks a lot, do you have any suggestion how to avoid invoking the `validate_{slot_name}` twice? Right now i'm using the same name for slot and entity, and i set the slot using entity `/intent_name{"entity_1": "value1"}` then after that i activate the form, that's why it's executing twice. value1 based on user input.

**Comment by Ghostvv** [comment]
I'd suggest to turn off auto filling of slots that are part of the form, as we do in formbot example: https://github.com/RasaHQ/rasa/blob/7fcfdd9eaa8704dc44ecbdb2927eb1a07b10d333/examples/formbot/domain.yml#L24

**Pull request closed without merging**
