### PR TITLE
Fix template response by ActionQueryKnowledgeBase to correctly use string representation of kb item.

### PR DESCRIPTION
**Pull request by kedz**
When using ActionQueryKnowldgeBase, the action utters a templated response to queries about the knowledge base items of the form: "'{NAME}' has the value '{VALUE}' for attribute '{ATTRIBUTE}'." NAME is supposed to be the string representation of the knowledge base item, however, it is currently returning the string representation of the function used to generate the string representation of the kb item. E.g.:

> '<function ActionMyKB.__init__.<locals>.<lambda> at 0x7fb23b7fddd0>' has the value 'True' for attribute 'breakfast-included'.

instead of 

> 'Hilton (Berlin)' has the value 'True' for attribute 'breakfast-included'.

This pull request fixes this bug so that templated responses produced by the action uses the string representation of the kb item.
In addition to fixing the bug in `rasa_sdk/knowledge_base/actions.py`, this pull request also modifies `tests/knowledge_base/test_actions.py` to check that templated responses are generated correctly.

Note: When I ran `make lint`, `black` suggested that the call signature for `run` (line 103 in  `rasa_sdk/knowledge_base/actions.py`) be on one line so I made that change as well.

### To Reproduce the Bug

```
cd rasa/examples/knowledgebasebot
rasa train
rasa run actions &
rasa shell
# Your input -> Hotels
# bot: Found the following objects of type 'hotel':
#    1: City Hotel (Frankfurt am Main)
#    2: Jugendherberge (Berlin)
#    3: Hilton (Frankfurt am Main)
#    4: Berlin Wall Hostel (Berlin)
#    5: B&B (Berlin)
# Your input -> does the last one offer breakfast?
# bot: Did not find a valid value for attribute 'breakfast-included' for object '<function ActionMyKB.__init__.<locals>.<lambda> at 0x7fb23b7fddd0>'.
```

**Status (please check what you already did)**:
- [X] made PR ready for code review
- [X] added some tests for the functionality
- [ ] updated the documentation (I don't think this is necessary?)
- [X] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/main/changelog) for instructions)
- [X] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

### CODE REVIEW

**Comment by kedz** [comment]
FYI: Looks like this has actually been proposed to be fixed before: https://github.com/RasaHQ/rasa-sdk/issues/365

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @rgstephens will take a look at it as soon as possible ✨

**Comment by wochinge** [comment]
@kedz Sorry, I'm on vacation from tomorrow till next Friday. Could you please request review by somebody else? 🙌🏻

**Comment by alwx** [comment]
Hey @kedz !

Thanks for your contribution.
Your PR looks good but there is a small issue with the code style? Could you please run `make formatter` to fix the issue with the code style?

**Review by alwx — APPROVED** [review]

**Comment by kedz** [comment]
Thanks @alwx ! I made the code style fix and added a changelog entry. I think this is good to merge?

**Comment by alwx** [comment]
Yes, perfect, thank you!

**Pull request merged**
