### PR TITLE
add resolutions in docs/package.json to fix vulnerabilities

### PR DESCRIPTION
**Pull request by m-vdb**
**Proposed changes**:
- Add "resolutions" to `package.json` to pin vulnerable libraries.
- ⚠️ I've ran `yarn why ...` to find out which dependencies depend on these libraries, and check that `redoc`, `netlify-cli` and `plugin-ideal-image` continue to work on dev and production build.

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

### CODE REVIEW

**Comment by m-vdb** [comment]
FYI @tczekajlo

**Comment by m-vdb** [comment]
@lunelson can you take a look at this PR when you get the chance? 🙏🏻

**Review by lunelson — APPROVED** [review]
Seems fine, as long as everything is still working 👍🏻. Might have to revisit these in future changes to theme, updating docusaurus etc. of course

**Comment by m-vdb** [comment]
FYI @tczekajlo I've just updated gitleaks GH action version for this repo in this commit 917295c

**Pull request merged**
