### PR TITLE
add type hints for dispatcher in Action

### PR DESCRIPTION
**Pull request by Dustyposa**
**Proposed changes**:
- Add type hint for `Action.run`'s `dispatcher` argument

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

### CODE REVIEW

**Comment by Dustyposa** [comment]
It's a simple change.

**Comment by Dustyposa** [comment]
Why failed.....

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @yennycheung will take a look at it as soon as possible ✨

**Comment by yennycheung** [comment]
Hi @Dustyposa, apologies for the late response. It seems that the CI checks are not yet passing, would you mind taking a look again?

**Comment by Dustyposa** [comment]
> Hi @Dustyposa, apologies for the late response. It seems that the CI checks are not yet passing, would you mind taking a look again?

@yennycheung I merged it from `main` master,  but the work flow not work, look like need your approve to run this workflow.
Thanks.

**Comment by yennycheung** [comment]
> > Hi @Dustyposa, apologies for the late response. It seems that the CI checks are not yet passing, would you mind taking a look again?
> 
> @yennycheung I merged it from `main` master, but the work flow not work, look like need your approve to run this workflow.
> Thanks.

Hm looks like the tests are still failing. If you do a `make test` locally, does it pass?

**Comment by Dustyposa** [comment]
> > > Hi @Dustyposa, apologies for the late response. It seems that the CI checks are not yet passing, would you mind taking a look again?
> > 
> > 
> > @yennycheung I merged it from `main` master, but the work flow not work, look like need your approve to run this workflow.
> > Thanks.
> 
> Hm looks like the tests are still failing. If you do a `make test` locally, does it pass?

Oh, my miss. Now I checked it and fixed it.

**Review by yennycheung — APPROVED** [review]

**Pull request merged**
